# Generated by Django 4.1 on 2023-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("isbn", models.CharField(max_length=17)),
                ("author", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("publisher", models.CharField(max_length=200)),
                ("img_url", models.URLField()),
                ("number_of_rating", models.IntegerField()),
            ],
        ),
    ]
